######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 9 17:24:48 2008
######################################################################

TEMPLATE = subdirs
SUBDIRS += spawn src protobuf
